/* Mike Henson 2015 */
void HelloWorld();
void Lab1_0();
void Lab1_1();
void Lab1_2();
void Lab1_3();
void Lab2_1();
void Lab2_2();
void Lab2_3();
void Lab2_4();
void Lab3_1();
void Lab3_2();
void Lab3_3();
void Lab3_4();
void Lab4_1();
void Lab4_2();
void Lab5_1();
void Lab5_2();
void Lab5_3();
void Lab5_4();
void Lab5_5();
void Lab5_6();
void Lab5_7();
void Lab5_8();
void Lab6_1();
void Lab6_2();
void Lab6_3();
void Lab7_1();
void Lab7_2();
void Lab7_3();
void Lab7_4();
void Lab8_1();
int Lab9_1();
int Lab9_2();
int Lab9_3();
extern unsigned long LabSize1_1;
extern unsigned long LabSize1_2;
extern unsigned long LabSize1_3;
extern unsigned long LabSize2_1;
extern unsigned long LabSize2_2;
extern unsigned long LabSize2_3;
extern unsigned long LabSize2_4;
extern unsigned long LabSize3_1;
extern unsigned long LabSize3_2;
extern unsigned long LabSize3_3;
extern unsigned long LabSize3_4;
extern unsigned long LabSize4_1;
extern unsigned long LabSize4_2;
extern unsigned long LabSize5_1;
extern unsigned long LabSize5_2;
extern unsigned long LabSize5_3;
extern unsigned long LabSize5_4;
extern unsigned long LabSize5_5;
extern unsigned long LabSize5_6;
extern unsigned long LabSize5_7;
extern unsigned long LabSize5_8;
extern unsigned long LabSize6_1;
extern unsigned long LabSize6_2;
extern unsigned long LabSize6_3;
extern unsigned long LabSize7_1;
extern unsigned long LabSize7_2;
extern unsigned long LabSize7_3;
extern unsigned long LabSize7_4;
extern unsigned long LabSize8_1;
extern unsigned long LabSize9_1;
extern unsigned long LabSize9_2;
extern unsigned long LabSize9_3;

